include config.mk

INTERMEDIATE_FILES = boot.elf boot.bin payload.elf payload.bin payload.hex0 simon.hex0
WRAPPED_BIN = simon_wrapped.img

all: $(FINAL_FLASH_IMG)
	@$(MAKE) --no-print-directory clean_tmp

$(YOUR_RAW_BIN): $(BOOT_SRC) $(PAYLOAD_SRC)
	$(CC) -march=rv64gc -mabi=lp64d -nostdlib -ffreestanding -Ttext=$(DDR_ADDR) $(BOOT_SRC) -o boot.elf
	$(OBJCOPY) -O binary boot.elf boot.bin
	$(CC) -march=rv64gc -mabi=lp64d -nostdlib -ffreestanding -Ttext=$(DDR_ADDR) $(PAYLOAD_SRC) -o payload.elf
	$(OBJCOPY) -O binary payload.elf payload.bin
	chmod +x ./bin-to-hex0.sh
	./bin-to-hex0.sh payload.bin payload.hex0
	cat boot.bin payload.hex0 payload.hex0 > $@

$(WRAPPED_BIN): $(YOUR_RAW_BIN)
	$(MKIMAGE) -A riscv -O u-boot -T standalone -C none \
		-a $(DDR_ADDR) -e $(DDR_ADDR) -n "SimonOS-Lichee" \
		-d $(YOUR_RAW_BIN) $@

$(FINAL_FLASH_IMG): $(WRAPPED_BIN)
	@test -f "$(SPL_BIN)" || (echo "Нет $(SPL_BIN). Положи рядом u-boot-with-spl.bin из builder-lichee"; exit 1)
	@echo "Собираем образ для SD-карты..."
	dd if=/dev/zero of=$@ bs=1M count=4
	dd if=$(SPL_BIN) of=$@ conv=notrunc
	dd if=$(WRAPPED_BIN) of=$@ bs=1k seek=1024 conv=notrunc
	@echo "ГОТОВО: $(FINAL_FLASH_IMG)"
	@echo "Шить примерно так: sudo dd if=$(FINAL_FLASH_IMG) of=/dev/sdX bs=4M status=progress conv=fsync"

qemu:
	$(MAKE) clean_tmp
	$(CC) -DQEMU -march=rv64gc -mabi=lp64d -nostdlib -ffreestanding -Ttext=0x80000000 $(BOOT_SRC) -o boot.elf
	$(OBJCOPY) -O binary boot.elf boot.bin
	$(CC) -DQEMU -march=rv64gc -mabi=lp64d -nostdlib -ffreestanding -Ttext=0x80000000 $(PAYLOAD_SRC) -o payload.elf
	$(OBJCOPY) -O binary payload.elf payload.bin
	./bin-to-hex0.sh payload.bin payload.hex0
	cat boot.bin payload.hex0 payload.hex0 > image_qemu.bin
	qemu-system-riscv64 -M virt -bios image_qemu.bin -monitor stdio

clean_tmp:
	@rm -f $(INTERMEDIATE_FILES) $(YOUR_RAW_BIN) $(WRAPPED_BIN)

clean:
	rm -f $(INTERMEDIATE_FILES) $(WRAPPED_BIN) $(YOUR_RAW_BIN) $(FINAL_FLASH_IMG) image_qemu.bin

.PHONY: all clean clean_tmp qemu
